# Generated by Django 5.2.3 on 2025-06-29 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_exercise_sets_workout_name_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='one_rep_max',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
    ]
